Data submission wf
icgc-argo/argo-docs pull request #555
Opened 2023-05-30 15:45 UTC by lindaxiang

2023-05-30 20:15 UTC, edsu7 commented on docs/submission/submitting-molecular-data.md
> +By default, it is assumed that Sequencing Reads are submitted from local storage. However if the Sequencing Reads are stored remotely in EGA Archives, it is easy to enable EGA download sub-workflow t
Formating edit:
By default, it is assumed that Sequencing Reads are submitted from local storage. However if the Sequencing Reads are stored remotely in EGA Archives, it is easy to enable EGA download sub-workflow to support getting data from EGA and submit to RDPC. The workflow also adds support to Sequencing Reads in CRAM format. For this, the reference genome is required to enable `cram2bam` step. Currently the workflow performs the following steps:

2023-05-30 20:21 UTC, edsu7 commented on docs/submission/submitting-molecular-data.md
> +Molecular data files are submitted in conjunction with necessary, descriptive data about molecular files and samples, called metadata. The DCC requires that metadata is submitted at the same time as
Molecular data files are submitted in conjunction with necessary, descriptive data about molecular files and samples, called metadata. The DCC requires metadata to be submitted at the same time as the molecular data to facilitate automated downstream analysis. The metadata is one of the mandatory inputs for the data submission workflow. Before proceeding, please read the instructions on how to prepare and format the metadata according to [molecular metadata model](/docs/submission/submitting-molecular-data#understanding-the-metadata-model) and [validation rules](/docs/submission/submitting-molecular-data#molecular-data-and-metadata-validation-rules).

2023-05-30 20:21 UTC, edsu7 commented on docs/submission/submitting-molecular-data.md
> +#### experiment
#### Experiment

2023-05-30 20:22 UTC, edsu7 commented on docs/submission/submitting-molecular-data.md
> +#### read_groups
```
#### Read_groups
```

2023-05-30 20:22 UTC, edsu7 commented on docs/submission/submitting-molecular-data.md
> +#### files
```
#### Files
```

2023-06-02 18:11 UTC, hknahal commented on docs/submission/submitting-molecular-data.md
> +The following describes the attributes and permissible values for all of the fields within the metadata tsv files for the ARGO Data Platform and Molecuar Data Processing.
Minor spelling typo: Molecu`l`ar

2023-06-09 17:51 UTC, edsu7 requested changes

2023-06-09 17:51 UTC, edsu7 commented on docs/submission/submitting-molecular-data.md
> +- DNA-Seq data from tumour and normal paired Whole Genome Sequencing (WGS) and Whole Exome Sequencing (WXS)
should we add target sequencing?

2023-06-09 17:51 UTC, edsu7 commented on docs/submission/submitting-molecular-data.md
> +- Fields `program_id`, `submitter_[donor|specimen|sample]_id` are `Required` and must be the same as what are submitted in `sample_registration` table.
```
Fields `program_id`, `submitter_[donor|specimen|sample]_id` are `Required` and must be the same values as the `sample_registration` table.
```

2023-06-27 20:34 UTC, edsu7 submitted a review, later dismissed
lgtm!

2023-06-29 13:55 UTC, justincorrigible submitted a review, later dismissed
LGTM 👍

2023-06-29 13:56 UTC, justincorrigible commented on website/sidebars.js
> -        'submission/molecular-data-prep',
not sure how does this affect the menu... with the filename changes in the two .md files in this PR.
guess we'll find out soon enough

2023-06-29 17:36 UTC, merged