Update molecular data submission with memory and docker platform settings
icgc-argo/argo-docs pull request #599
Opened 2024-03-12 20:25 UTC by guanqiaofeng

Updated submitting-molecular-data.md documentation for  
1) local runtime environment (required memory exceeds available memory) and  
2) docker platform variable for Apple M1 users

2024-03-12 20:25 UTC, guanqiaofeng commented
https://github.com/icgc-argo/argo-docs/pull/592

2024-03-13 14:10 UTC, edsu7 requested changes

2024-03-13 14:10 UTC, edsu7 commented on docs/submission/submitting-molecular-data.md
> +- If data is submitted through a laptop, users may come across issue that required memory exceeds available memory. In such case, add `--score_mem 16 --score_cpus 2` in the nextflow command. The requ
`users may come across issue that required memory exceeds available memory`
to
`users may encounter hardware resource limitations`

To be less verbose

2024-03-13 14:10 UTC, edsu7 commented on docs/submission/submitting-molecular-data.md
> +- If local computer has Mac M1 (ARM64) system, you may run into docker platform issue. To solve this issue, users can add `export DOCKER_DEFAULT_PLATFORM=linux/amd64` before executing the nextflow pi
```
To run docker on ARM64 systems,  users can execute `export DOCKER_DEFAULT_PLATFORM=linux/amd64` in the terminal before executing the nextflow pipleline
```

2024-03-13 14:20 UTC, guanqiaofeng commented
updated based on Edmund's suggestions

2024-03-13 14:39 UTC, edsu7 approved these changes
LGTM!

2024-03-13 15:35 UTC, merged